# Custom Favicon
favicon: favicon.png
# Site name
name: Linaro Developer Cloud
# Site Slogan
slogan: An openstack powered cloud for development in the ARMv8 server ecosystem.
# Mailchimp settings
mailchimp:
    enabled: true
    id: af6cf590b0
    unsubscribe-url: https://linaro.us3.list-manage.com/unsubscribe?u=14baaae786342d0d405ee59c2&id=af6cf590b0
# Footer Newsletter toggle.
newsletter:
    enabled: false
tags_enabled: true
# Footer Image default is linaro sprinkle
linaro-footer-image: Linaro-Sprinkle.png
# # Breadcrumb Settings
# breadcrumb:
#     image: breadcrumb-image.jpg
#Content Repo for static site.
# Used for the edit on github include
edit-on-github:
    enabled: false
    repo: https://www.github.com/Linaro/cloud
jumbotron:
    # Darken is set to true by default - if you wish to remove the image overlay
    # then change this setting to false.
    darken: true
error-pages:
  # image: /assets/images/content/path-to-image.jpg
  svg: linaro-404.html
  not-found-title: 404 page not found!
  not-found-desc: Sorry, but the page you were looking for could not be found.
# Jekyll social media site settings. Github, LinkedIn, Google+, Facebook and Youtube
github_username: Linaro
linkedin_username: 1026961
facebook_username: LinaroOrg
youtube_username: linaroorg
twitter_username: linaroorg
slideshare_username: linaroorg
# Blog setup
blog:
    # Show Thumbnails in the post index
    show_thumbnails: true
    # Toggle site wide comments display.
    comments: true
    # Post Side Bar Settings
    sidebar:
        display-on-posts: true
        display-on-index: true
        # Toggle whether or not thumbnails in the sidebar are displayed.
        thumbnails:
            display: true
        # Display other posts contained in _posts
        other-posts:
            display: true
            count: 4
        # Display Related posts based on tags / categories
        related-posts:
            display: true
            count: 5
        # Display the most recent posts
        most-recent-posts:
            display: true
            count: 5
        # Display custom collection e.g projects on 96boards
        collection:
            - name: projects
              count: 5
              # Fields to use for title and url.
              display_fields:
                  title: title
                  url: url
# Google Anayltics Setup
google:
    analytics: UA-16756069-19

# Shema.org settings used in the schema.html include.
schema:
    enabled: false
    organisation:
        name: Linaro
        url: https://www.linaro.org
        sameAs:
            - https://twitter.com/linaroorg
            - https://www.facebook.com/LinaroOrg
            - https://www.linkedin.com/company/1026961/
            - https://plus.google.com/+LinaroOnAir
            - https://github.com/Linaro
            - https://www.slideshare.net/linaroorg
        address:
            street: Harston Mill, Royston Rd 
            town: Harston 
            county: Cambridge 
            post_code: CB22 7GG
            country_code: UK
# Disqus Comments
disqus:
    enabled: true
    shortname: Linaro
# Placeholder for Missing Images
placeholder: linaro-logo.png
